name: GitHub Actions Demo

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Installing dependencies
        run: npm install
      - name: Creating README.md
        run: touch README.md
      - name: Starting node
        run: npm run compile